# Generated by Django 2.1.7 on 2019-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('comentario', '0001_initial'),
        ('atracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('atracao', models.ManyToManyField(to='atracao.Atracao')),
                ('avaliacao', models.ManyToManyField(to='avaliacao.Avaliacao')),
                ('comentario', models.ManyToManyField(to='comentario.Comentario')),
            ],
        ),
    ]
