# Generated by Django 2.2 on 2019-04-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190401_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='foto',
        ),
    ]
