# Generated by Django 2.1.7 on 2019-03-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atracoes'},
        ),
    ]
